name: stammtisch_manager
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.9
  provider: ^6.0.2
  table_calendar: ^3.0.4
  intl: ^0.17.0
  google_fonts: ^2.3.1
  flutter_datetime_picker: ^1.5.1
  flutterfire_ui: ^0.3.6+1
  firebase_auth: ^3.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
