// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVc-tMKmNo3aHTxeJotMdmr7xTNB6grjk',
    appId: '1:447187833757:web:e1c8b06abd852283d91574',
    messagingSenderId: '447187833757',
    projectId: 'stammtisch-manager',
    authDomain: 'stammtisch-manager.firebaseapp.com',
    storageBucket: 'stammtisch-manager.appspot.com',
    measurementId: 'G-KZHC4Q5SZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy75xunABGnZ5W3uI4uIyFTIdo6cTJKCw',
    appId: '1:447187833757:android:c66cb931541e00fcd91574',
    messagingSenderId: '447187833757',
    projectId: 'stammtisch-manager',
    storageBucket: 'stammtisch-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPbAV8isS_G62KYeLldCKGJigEj8KMSBU',
    appId: '1:447187833757:ios:297a094ee1ec0b90d91574',
    messagingSenderId: '447187833757',
    projectId: 'stammtisch-manager',
    storageBucket: 'stammtisch-manager.appspot.com',
    iosClientId: '447187833757-buuqb2soeid5uph7mvbncg6rgi5j18ve.apps.googleusercontent.com',
    iosBundleId: 'com.stammtisch-manager',
  );
}
